apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
        # matchExpressions:
        # - key: target
        #   operator: NotIn
        #   values:
        #   - local
  template:
    metadata:
      name: '{{ .name }}-cluster'
      namespace: argocd
    spec:
      project: genesis
      source:
        repoURL: https://github.com/iverberk/opsteady-poc.git
        targetRevision: HEAD
        path: '{{ .name }}'
      destination:
        name: genesis
        namespace: argocd
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated: {}
