apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: opsteady
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  strategy:
    type: RollingSync
    rollingSync:
      steps:
      - matchExpressions:
        - key: app
          operator: In
          values:
          - argocd
  generators:
    - git:
        repoURL: https://github.com/iverberk/opsteady-poc.git
        revision: HEAD
        files:
          - path: apps/**/app.yaml
  template:
    metadata:
      name: 'opsteady-{{ .name }}'
      labels:
        app: '{{ .name }}'
    spec:
      project: opsteady
      source:
        repoURL: https://github.com/iverberk/opsteady-poc.git
        path: '{{ .path.path }}'
        targetRevision: HEAD
        helm:
          releaseName: '{{ .name }}'
          valuesObject:
            name: '{{ .name }}'
            cluster: opsteady
      destination:
        name: opsteady
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
