---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: opsteady
  namespace: argocd
spec:
  description: opsteady project
  sourceRepos:
  - '*'
  sourceNamespaces:
  - '*'
  destinations:
  - name: opsteady
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
