---
environments:
  genesis:
    values:
    - childClusters: true
      parentCluster: genesis

  opsteady:
    values:
    - childClusters: true
      parentCluster: genesis

  opsteady-wl:
    values: []
