---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: genesis
  namespace: argocd
spec:
  description: genesis project
  sourceRepos:
  - '*'
  sourceNamespaces:
  - '*'
  destinations:
  - name: genesis
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
