apiVersion: v1
kind: Secret
metadata:
  name: genesis
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: genesis
  server: https://kubernetes.default.svc
  config: |-
    {
      "tlsClientConfig":{
        "insecure":false
      }
    }

